# Numpy

In [27]:
import numpy  as np

# Vectores y Matrices

In [4]:
vector=np.array([0,1,2,3,4,5])
print(vector)

[0 1 2 3 4 5]


In [7]:
#Formas de cambiar de tipo de dato un vector
vectorDos=np.array([1,2,3,4,5], dtype=np.float32)
print(vectorDos)

#Formas de cambiar de tipo de dato un vector
vector.dtype=np.float16
print(vector)

# Esta es la forma correcta de cambiar el tipo de dato de un vector
vectorTres=np.array([1,2,3,4,5])
vectorTre=vectorTres.astype(np.float16)
print(vectorTres)

[1. 2. 3. 4. 5.]
[0.0e+00 0.0e+00 6.0e-08 0.0e+00 1.2e-07 0.0e+00 1.8e-07 0.0e+00 2.4e-07
 0.0e+00 3.0e-07 0.0e+00]
[1 2 3 4 5]


In [9]:
#Acceso a la informacion de un vector con numpy
print(vectorTres[3])


4


In [11]:
vectorCuatro=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(vectorCuatro[0:8:2])

[0 2 4 6]


## Operaciones con Matrices y Vectores

In [18]:

a=np.array([0,1,2])
b=np.array([0,-1,-3])
c=np.array([1,1,1])

print(a+b)
print(a-b)

print(a*b)
print(a/c)
print(3*a)
print(a>=1)
demo=a>=1
print(demo)

print(a**a)

[ 0  0 -1]
[0 2 5]
[ 0 -1 -6]
[0. 1. 2.]
[0 3 6]
[False  True  True]
[False  True  True]
[1 1 4]


In [21]:
#Creacion de vectores
print(np.linspace(0,15,15)) # Del numero 0 al numero 15 reaizaremos una resta, dividida en 15 elementos
print(np.arange(0,15,1)) #Intervalo abierto 

[ 0.          1.07142857  2.14285714  3.21428571  4.28571429  5.35714286
  6.42857143  7.5         8.57142857  9.64285714 10.71428571 11.78571429
 12.85714286 13.92857143 15.        ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [23]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Redimencionamiento de Matrices y vectores

In [33]:
# Para utilizar shape la matriz tiene que ser homogenea:3x3, 4x4, 5x5 etc.
print(matrix.shape)
a= np.arange(0,16,1)
print(a.shape)
nueva=matrix.reshape(9,) # Redimencionamos la matriz, de una matriz pasa a un vector
print(nueva)
print(matrix)
b= a.reshape(2,8)
print(b)

(3, 3)
(16,)
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


Union de Matrices

In [36]:
mt1=[[34,3],[67,7]]
mt2=[[11,2],[78,3]]
mt3=[[23,32],[90,1]]
arr1=np.array([mt1,mt2,mt3])
print(arr1.shape)

(3, 2, 2)


Indexacion con cortes

In [50]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(m.shape)
print("---------------------")
c1=m[:2,1]
c1=m[:2,1:3] #Primer valor para las filas, segundo valor para las columnas y el ultimo para indicar de donde a donde
c2=m[2] #Obtenemos vectoe
print(c1)
print(c2[1])#Obtenemos elemento

#Otra forma de acceder a los elemtnos
c2=m[2:,:]
print(c2.shape) #Nos indica el numero de filas y columnas: 1 fila y 3 columnas
print(c2[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
---------------------
[[2 3]
 [5 6]]
8
(1, 3)
8


$$ Determinastes-Inversas $$

In [54]:
A=np.array([[2,-1],[1,3]])
B=np.array([3,5])
c=np.linalg.solve(A,B)
print(c)
print(A@c)# Multiplicacion de matrices

[2. 1.]
[3. 5.]
