# Tarea Vectores u Arreglos

## *Avendaño Villegas Brandon*

Primer Problema
---
Llamamos matriz cero y se denota O, la cual contiene muchos ceros, comprobar las siguientes
propiedades:

$$
\left(\begin{array}{cc} 
1 & 4\\
-1 & 3\\
2 & -9
\end{array}\right) $$


$$ A + O = A − O = A $$
$$ A − A = O $$

In [4]:
import numpy as np

In [3]:
A=np.array([[1,4],[-1,3],[1,-9]])
cero= np.zeros((3,2))
r=A-A
print(r)
print("--------------------")


[[0 0]
 [0 0]
 [0 0]]
--------------------


In [4]:
A=np.array([[3,0],[-1,3],[2,-9]])
cero=np.zeros((3,2))
r=A-A
print(r)

[[0 0]
 [0 0]
 [0 0]]


Segundo Problema
---
Sea
$$
A= \left[\begin{array}{cc} 
3 & 0\\
-1 & 5
\end{array}\right] 
$$

$$
B= \left[\begin{array}{cc} 
4 & -2 & 1\\
0 & 2 & 3
\end{array}\right]
$$

1. $A+3B$
2. $AB$
4. $A^3$
5. $B^2$
7. $(5A)B$

In [10]:
A=np.array([[3,0],[-1,5]])

B=np.array([[4,-2,1],[0,2,3]])

# A + 3B
result1 = A + 3 * B[:, :2]  # Se seleccionan las dos primeras columnas de B para que las dimensiones sean compatibles
print("A + 3B:")
print(result1)

# AB
result2 = np.dot(A, B)
print("AB:")
print(result2)

# A^3
result3 = np.linalg.matrix_power(A, 3)
print("A^3:")
print(result3)

# B^2
result4 = np.dot(B, B.T)  # Se realiza la multiplicación de B con su transpuesta para obtener la potencia 2
print("B^2:")
print(result4)

# (5A)B
result5 = np.dot(5 * A, B)
print("(5A)B:")
print(result5)

A + 3B:
[[15 -6]
 [-1 11]]
AB:
[[12 -6  3]
 [-4 12 14]]
A^3:
[[ 27   0]
 [-49 125]]
B^2:
[[21 -1]
 [-1 13]]
(5A)B:
[[ 60 -30  15]
 [-20  60  70]]


Tercer Problema
---
Dos restaurantes desean comprar frutas para la siguiente semana. La tabla 1 muestra que tipo
de fruta y cantidad desean adquirir. Se tienen dos centros comerciales, la tabla 2 muestra sus
precios. ¿Cuánto costara comprar las frutas para cada uno de los centros comerciales?

* Tabla 1

|                | Naranjas       | Manzanas |Piñas        |
|----------------|:--------------:|:----------:|:---------:|
|Restaurante Uno | 30             | 15         |4          |
|Restaurante Dos | 25             | 18         |8          |

* Tabla 2

|                     | Naranjas       | Manzanas   |Piñas      |
|---------------------|:--------------:|:----------:|:---------:|
|Centro Comercial Uno | 1.2            | 2.2        |4.5        |
|Centro Comercial Dos | 1.3            | 2.1        |4.6        |

In [6]:
fruits = np.array([[30, 15, 4], [25, 18, 8]])
prices = np.array([[1.2, 2.2, 4.5], [1.3, 2.1, 4.6]])

# Calcular el costo de frutas para cada centro comercial
costs = np.dot(fruits, prices.T)
print("Costos de frutas para cada centro comercial:")
print(costs)

Costos de frutas para cada centro comercial:
[[ 87.   88.9]
 [105.6 107.1]]


Cuarto Problema
---
Una fábrica elabora tres productos (escobas, escobetas, cepillos) y los envía a dos almacenes
para su cuidado. El número de unidades esta dado en la tabla 

* Tabla 3

|          |     |   |
|----------|:---:|:-:|
|Escobas   | 30  | 15|
|Escobetas | 25  | 18|
|Cepillos  | 100 |125|

El costo de embarcar por camión es por cada unidad de escoba es 1.50, escobetas 1.00 y cepillos
2.00, el costo por tren es escoba es 1.75, escobetas 1.50 y cepillos 1.00. Organizar la información
en una matriz, para ocupar la multiplicación de matrices, dependiendo de los resultados, indica
que le conviene a la empresa embarcar con camión o tren.

In [11]:
# Definir la tabla de unidades y costos de embarque
units = np.array([[30, 15], [25, 18], [100, 125]])
truck_cost = np.array([1.5, 1.0, 2.0])
train_cost = np.array([1.75, 1.5, 1.0])

# Calcular el costo total de embarque por camión y tren
total_truck_cost = np.sum(units * truck_cost.reshape(3, 1), axis=0)
total_train_cost = np.sum(units * train_cost.reshape(3, 1), axis=0)

# Comparar los costos y determinar la opción más económica
if np.sum(total_truck_cost) < np.sum(total_train_cost):
    print("Es más económico embarcar por camión.")
else:
    print("Es más económico embarcar por tren.")

Es más económico embarcar por tren.


5. Resolver el siguiente sistema de ecuaciones

$$3x + 2y = 6$$
$$6x + 4y = −9$$

$$x + y = 3$$
$$x − 4y = 1$$

$$2x − y + 2z = 3$$
$$2x + 3y − z = 0$$
$$x + 2y + 2z = −12$$

In [12]:
# Definir los coeficientes y los términos constantes del sistema de ecuaciones
coefficientsSis1 = np.array([[3,2],[6,4]])
coefficientsSis2 = np.array([[1, 1], [1, -4]])
coefficientsSis3 = np.array([[2, -1, 2], [2, 3, -1], [1, 2, 2]])

constantsSis1 = np.array([6,-9])
constantsSis2 = np.array([3, 1])
constantsSis3 = np.array([3, 0, -12])

# Obtener la solución del sistema de ecuaciones
solutionSis1 = np.linalg.lstsq(coefficientsSis1, constantsSis1)
solutionSis2 = np.linalg.solve(coefficientsSis2, constantsSis2)
solutionSis3 = np.linalg.solve(coefficientsSis3, constantsSis3)
print("Solución del sistema de ecuaciones 1:")
print(solutionSis1)
print("------------------------------------------")
print("Solución del sistema de ecuaciones 2:")
print(solutionSis2)
print("------------------------------------------")
print("Solución del sistema de ecuaciones 3:")
print(solutionSis3)

Solución del sistema de ecuaciones 1:
(array([-0.55384615, -0.36923077]), array([], dtype=float64), 1, array([8.06225775e+00, 3.69504558e-16]))
------------------------------------------
Solución del sistema de ecuaciones 2:
[2.6 0.4]
------------------------------------------
Solución del sistema de ecuaciones 3:
[ 3.65217391 -3.7826087  -4.04347826]


C:\Users\angel\AppData\Local\Temp\ipykernel_18032\2441940689.py:11: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solutionSis1 = np.linalg.lstsq(coefficientsSis1, constantsSis1)
