# Segunda tanda de Ejercicios

In [35]:
a=[2,4]
b=[16,32,96]
a.sort()
b.sort()
sc=[]
for i in range(a[-1],b[0]+1):
    for n in a:
        if i%n==0:
            for m in b:
                if m%i==0:
                    sc.append(i)
        elif i%m!=0 and i in sc:
            sc.remove(i)
print(list(set(sc)))

[8, 16, 4, 12]


Primer Problema
---
Llamamos matriz cero y se denota O, la cual contiene muchos ceros, comprobar las siguientes
propiedades:

$$
\left(\begin{array}{cc} 
1 & 4\\
-1 & 3\\
2 & -9
\end{array}\right) $$


$$ A + O = A − O = A $$
$$ A − A = O $$

In [2]:
import numpy as np

In [15]:
A=np.array([[1,4],[-1,3],[1,-9]])
cero= np.zeros((3,2))
r=A-A
print(r)
print("--------------------")


[[0 0]
 [0 0]
 [0 0]]
--------------------


In [7]:
A=np.array([[3,0],[-1,3],[2,-9]])
cero=np.zeros((3,2))
r=A-A
print(r)

[[0 0]
 [0 0]
 [0 0]]


Segundo Problema
---
Sea
$$
A= \left[\begin{array}{cc} 
3 & 0\\
-1 & 5
\end{array}\right] 
$$

$$
B= \left[\begin{array}{cc} 
4 & -2 & 1\\
0 & 2 & 3
\end{array}\right]
$$

1. $A+3B$
2. $AB$
4. $A^3$
5. $B^2$
7. $(5A)B$

In [39]:
A=np.array([[3,0],[-1,5]])

b=np.array([[4,-2,1],[0,2,3]])
B=b.reshape(3,2) #Redimencionamos la matriz para operar con ella
print(B)
uno=A+(B*3)
print(uno)
dos=A@B
print(dos)
tres=A@A@A
print(tres)
cuatro=B@B
print(cuatro)
cinco=(5*A)*B
print(cinco)

[[ 4 -2]
 [ 1  0]
 [ 2  3]]


ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

Tercer Problema
---
Dos restaurantes desean comprar frutas para la siguiente semana. La tabla 1 muestra que tipo
de fruta y cantidad desean adquirir. Se tienen dos centros comerciales, la tabla 2 muestra sus
precios. ¿Cuánto costara comprar las frutas para cada uno de los centros comerciales?

* Tabla 1

|                | Naranjas       | Manzanas |Piñas        |
|----------------|:--------------:|:----------:|:---------:|
|Restaurante Uno | 30             | 15         |4          |
|Restaurante Dos | 25             | 18         |8          |

* Tabla 2

|                     | Naranjas       | Manzanas   |Piñas      |
|---------------------|:--------------:|:----------:|:---------:|
|Centro Comercial Uno | 1.2            | 2.2        |4.5        |
|Centro Comercial Dos | 1.3            | 2.1        |4.6        |

Cuarto Problema
---
Una fábrica elabora tres productos (escobas, escobetas, cepillos) y los envía a dos almacenes
para su cuidado. El número de unidades esta dado en la tabla 

* Tabla 3

|          |     |   |
|----------|:---:|:-:|
|Escobas   | 30  | 15|
|Escobetas | 25  | 18|
|Cepillos  | 100 |125|

El costo de embarcar por camión es por cada unidad de escoba es 1.50, escobetas 1.00 y cepillos
2.00, el costo por tren es escoba es 1.75, escobetas 1.50 y cepillos 1.00. Organizar la información
en una matriz, para ocupar la multiplicación de matrices, dependiendo de los resultados, indica
que le conviene a la empresa embarcar con camión o tren.